package com.app.quantitymeasurement.model;

import java.time.LocalDateTime;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * QuantityMeasurementEntity
 *
 * This is the database entity class. Every quantity operation performed in the
 * application is stored as one row in this table.
 *
 * Important: Repository methods use field names directly. So field must be
 * named 'error', not 'isError'.
 */
@Entity
@Table(name = "quantity_measurement")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class QuantityMeasurementEntity {

	/**
	 * Primary key
	 *
	 * Auto-generated by database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * First quantity details
	 */
	private Double thisValue;
	private String thisUnit;
	private String thisMeasurementType;

	/**
	 * Second quantity details
	 */
	private Double thatValue;
	private String thatUnit;
	private String thatMeasurementType;

	/**
	 * Operation type
	 *
	 * Example: compare, convert, add, subtract, divide
	 */
	private String operation;

	/**
	 * Result fields
	 *
	 * resultValue/resultUnit/resultMeasurementType are used for
	 * convert/add/subtract/divide
	 *
	 * resultString is used for compare
	 */
	private Double resultValue;
	private String resultUnit;
	private String resultMeasurementType;
	private String resultString;

	/**
	 * Error-related fields
	 *
	 * IMPORTANT: Keep field name as 'error' so repository methods like
	 * findByErrorTrue() and countByOperationAndErrorFalse() work correctly.
	 */
	@Column(name = "is_error")
	private boolean error;

	private String errorMessage;

	/**
	 * Timestamp of record creation
	 */
	private LocalDateTime createdAt = LocalDateTime.now();

	/**
	 * Constructor for compare operation
	 *
	 * Used when result is true/false string.
	 */
	public QuantityMeasurementEntity(Double thisValue, String thisUnit, String thisMeasurementType, Double thatValue,
			String thatUnit, String thatMeasurementType, String operation, String resultString) {

		this.thisValue = thisValue;
		this.thisUnit = thisUnit;
		this.thisMeasurementType = thisMeasurementType;

		this.thatValue = thatValue;
		this.thatUnit = thatUnit;
		this.thatMeasurementType = thatMeasurementType;

		this.operation = operation;
		this.resultString = resultString;
		this.error = false;
	}

	/**
	 * Constructor for arithmetic / conversion operations
	 *
	 * Used for add, subtract, divide, convert.
	 */
	public QuantityMeasurementEntity(Double thisValue, String thisUnit, String thisMeasurementType, Double thatValue,
			String thatUnit, String thatMeasurementType, String operation, Double resultValue, String resultUnit,
			String resultMeasurementType) {

		this(thisValue, thisUnit, thisMeasurementType, thatValue, thatUnit, thatMeasurementType, operation,
				(String) null);

		this.resultValue = resultValue;
		this.resultUnit = resultUnit;
		this.resultMeasurementType = resultMeasurementType;
	}

	/**
	 * Constructor for failed operations
	 *
	 * Used when operation throws exception and we still want to store failure
	 * history.
	 */
	public QuantityMeasurementEntity(Double thisValue, String thisUnit, String thisMeasurementType, Double thatValue,
			String thatUnit, String thatMeasurementType, String operation, String errorMessage, boolean error) {

		this(thisValue, thisUnit, thisMeasurementType, thatValue, thatUnit, thatMeasurementType, operation,
				(String) null);

		this.errorMessage = errorMessage;
		this.error = error;
	}
}